import Footer from '@/components/footer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <link rel="preconnect" href="https://fonts.googleapis.com"></link>
            <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin
            ></link>
            <link
                href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap"
                rel="stylesheet"
            ></link>
            <body className={inter.className}>
                <Header />
                {children}

                <Footer />
            </body>
        </html>
    )
}
